using Core.Entities;

namespace ReverseProxyManager.Requests
{
    public class EditServerRequest
    {
        public string Name { get; set; }

        public bool Active { get; set; } = false;

        public string Target { get; set; }

        public long TargetPort { get; set; }

        public bool UsesHttp { get; set; } = false;

        public int CertificateId { get; set; } = -1;

        public bool RedirectsToHttps { get; set; } = true;

        // Is only used when the autogenerated code is not enough.
        // This is basically replacing everything thats automatically gets generated for the default.conf
        // Use at yout own risk
        public string? RawSettings { get; set; } = null;

        public DateTime LastUpdated { get; set; } = DateTime.Now;
    }
}
