import { IdNameDto } from "./certificateModels";

export interface ServerDto{
        id: number;

        name: string;

        active: boolean;

        target:string;

        targetPort: number;

        isUpToDate: boolean;

        usesHttp: boolean;

        certificate:IdNameDto | null;

        redirectsToHttps: boolean;

        // Is only used when the autogenerated code is not enough.
        // This is basically replacing everything thats automatically gets generated for the default.conf
        // Use at yout own risk
        rawSettings: string | null;

        lastUpdated: Date;
}