using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core.Entities
{
    public class ServerEntity
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public bool Active { get; set; } = false;

        public string Target { get; set; }

        public long TargetPort { get; set; }

        public bool IsUpToDate { get; set; } = false;   

        public bool UsesHttp { get; set; } = false;

        public CertificateEntity? Certificate { get; set; } = null;

        public bool RedirectsToHttps { get; set; } = true;

        // Is only used when the autogenerated code is not enough.
        // This is basically replacing everything thats automatically gets generated for the default.conf
        // Use at yout own risk
        public string? RawSettings { get; set; } = null;

        public DateTime LastUpdated { get; set; } = DateTime.Now;
    }
}
