name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -f ./ReverseProxyManager/ReverseProxyManager/Dockerfile --tag reverse-proxy-manager:$(date +%s) --build-arg "BUILD_CONFIGURATION=Release" "./ReverseProxyManager/ReverseProxyManager"
  
